[package]
name = "program"
version = "0.1.0"
edition = "2021"

[dependencies]
common = { path = "../common" }
borsh = "1.5.7"
solana-program = "2.2.1"
spl-token = { version = "8.0.0", features = ["no-entrypoint"] }

[lib]
crate-type = ["cdylib", "lib"]
